### ISSUE TITLE
Integrate pathom

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro-lein-template#10]
I think pathom is a significant enough library that it deserves to be the server-side default for the template.  It would be nice to beef up the demo UI a bit, and include a pathom back-end.  I'll do this soon unless @wilkerlucio wants to drop something in?

**Comment by wilkerlucio** [comment]
I think would be great to have a pathom setup built-in, I don't have the time now to look into it, but let me know if you need help any specific thing. The only important thing I like to mention is that I'm about to change as bit the connect boilerplate, with the updates from the yesterday that will change a bit (the current/old way will still work, but I will encourage something a bit different from now on).

**Comment by awkay** [comment]
Done.
